[tool.project-metadata]
name = "Palo Alto Plugin"
description = "A plugin for the AI assistant app, enhancing it with Palo Alto capabilities."
version = "1.0.2"

[tool.versioning]
major = 1
minor = 0
patch = 2
