# Definitions to parse Data Content Filtering events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.

data:
  description: ""
  message: "Data/Data Filtering: {self.event}"

dlp:
  description: ""
  message: "Data/DLP: {self.event}"

dlp-non-file:
  description: ""
  message: "Data/DLP non file: {self.event}"

file:
  description: ""
  message: "Data/File: {self.event}"

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
