# Definitions to parse Global Protect events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.


portal-auth:
  description: "GlobalProtect portal authentication stage"
  message: "GP/portal-auth: {self.event}"
portal-auth_error:
  description: "GlobalProtect portal authentication stage, error condition"
  message: "{self.gp_client_srcuser} in the {self.gp_client_srcregion} region had an error authenticating to the {self.gp_portal} portal on {self.device_name} from {self.gp_client_publicip}. Error: {self.gp_event_error}."
portal-gen-cookie:
  description: "GlobalProtect portal authentication override cookie generation event"
  message: "GP Portal: {self.event}"
portal-getconfig:
  description: "Generating GlobalProtect client configuration, such as dynamic app configuration or gateway list"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} has requested a configuration from the {self.gp_portal} portal on {self.device_name}. Description: {self.gp_event_description}."
portal-prelogin:
  description: "GlobalProtect portal pre-login event: Checks certificate, generates SAML request, triggers kerberos authentication"
  message: "{self.gp_client_authmethod} pre-login request for {self.gp_portal} portal on {self.device_name}. Request is from {self.gp_client_publicip} in the {self.gp_client_srcregion} region."

gateway-agent-msg:
  description: "GlobalProtect gateway event for a message received from the GlobalProtect client, such as GlobalProtect client disable reason message"
  message: "Update from {self.gp_client_srcuser} on {self.gp_client_hostname} for {self.gp_portal} portal on {self.device_name}. Message: {self.gp_event_description}."
gateway-auth:
  description: "Indicates GlobalProtect gateway authentication stage"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} has authenticated to the {self.gp_gateway} gateway on {self.device_name} using {self.gp_client_authmethod}. Gateway selection was {self.gp_selection} with priority {self.gp_priority}."
gateway-config-release:
  description: "Indicates a GlobalProtect gateway event for configuration release, such as remove ip-user mapping or remove tunnel"
  message: "Config release for {self.gp_client_srcuser} on {self.gp_client_hostname}"
gateway-connected:
  description: "Client successful connection for tunnel or non-tunnel mode"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} has connected to the {self.gp_portal} portal on {self.device_name}."
gateway-framed-ip:
  description: "Indicates a GlobalProtect gateway event where the gateway retrieved a framed IPv4 address from RADIUS for a GlobalProtect client"
  message: "GP Gateway: {self.event}"
gateway-getconfig:
  description: "Generating GlobalProtect client configuration, such as split-tunnel, virtual IP, or tunnel information"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} has requested a configuration from the {self.gp_portal} portal on {self.device_name}. Description: {self.gp_event_description}."
gateway-hip-check:
  description: "Confirm whether a GlobalProtect HIP report was updated or not, and to refresh ip-user mapping"
  message: "Gateway HIP check for {self.gp_client_srcuser} on {self.gp_client_hostname}: {self.gp_event_description}"
gateway-hip-report:
  description: "Confirm whether a HIP report was received from a GlobalProtect client, to update ip-user mapping, and to enforce HIP policy"
  message: "Gateway HIP report for {self.gp_client_srcuser} on {self.gp_client_hostname}. Host information collected."
gateway-hip-report_error:
  description: "An error with a HIP report"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} had an error sending a HIP report to the GP gateway on {self.device_name}. Stage: {self.gp_event_stage}, status: {self.gp_event_status}, error: {self.gp_event_error}."
gateway-inheritance:
  description: "GlobalProtect gateway is using a dynamic IP address and the IP address changed"
  message: "GP Gateway: {self.event}"
gateway-logout:
  description: "Client logout"
  message: "{self.gp_client_srcuser} has logged out from the {self.gp_portal} portal on {self.device_name}."
gateway-prelogin:
  description: "Checks certificate, generates SAML request, triggers kerberos authentication"
  message: "Gateway prelogin for {self.gp_portal} portal on {self.device_name}. Request is from {self.gp_client_publicip} in the {self.gp_client_srcregion} region."
gateway-register:
  description: "Indicates GlobalProtect client user information, such as username, domain-name, computer name, hostid, serial number, public ip, or login time is added on the gateway"
  message: "GP/Gateway_Register: {self.event}"
gateway-register_error:
  description: "An error with the gateway register event"
  message: "{self.gp_client_hostname}/{self.gp_client_srcuser} had an error registing with the GP gateway on {self.device_name}. Stage: {self.gp_event_stage}, status: {self.gp_event_status}, error: {self.gp_event_error}."
gateway-setup-ipsec:
  description: "Indicates a GlobalProtect gateway event for setting up an IPSec VPN tunnel"
  message: "Setting up IPSec tunnel for {self.gp_client_srcuser} on {self.gp_client_hostname}. Portal: {self.gp_portal} on {self.device_name}."
gateway-setup-ssl:
  description: "Indicates a GlobalProtect gateway event for setting up a SSL VPN tunnel"
  message: "GP Gateway: {self.event}"
gateway-switch-to-ssl:
  description: "Indicates a GlobalProtect gateway tunnel switch from IPSec to SSL considering IPSec tunnel was not successful"
  message: "{self.gp_client_srcuser} on {self.gp_client_hostname} is switching to SSL tunnel for {self.gp_portal} portal on {self.device_name}."
gateway-tunnel-latency:
  description: "GlobalProtect gateway latency provided by a GlobalProtect client"
  message: "Tunnel latency measured for {self.gp_client_srcuser} on {self.gp_client_hostname}: {self.gp_event_description}"
gateway-tunnel-notify:
  description: "Not documented, but it seems to be an update in the GlobalProtect tunnel status"
  message: "Update for {self.gp_client_srcuser}'s tunnel status: {self.gp_event_description}"

quarantine-add:
  description: "The client is added to the quarantine list"
  message: "GP Gateway: {self.event}"
quarantine-delete:
  description: "The client is removed from the quarantine list"
  message: "GP Gateway: {self.event}"

clientlessvpn-login:
  description: "Portal event for GlobalProtect Clientless VPN login"
  message: "GP Clientless VPN: {self.event}"
clientlessvpn-logout:
  description: "Portal event for GlobalProtect Clientless VPN logout"
  message: "GP Clientless VPN logout. {self.gp_client_publicip} logged out from {self.gp_portal} portal on {self.device_name}."
clientlessvpn-prelogin:
  description: "Indicates a GlobalProtect portal pre-login event: Checks certificate, generates SAML request, triggers kerberos authentication"
  message: "GP Clientless VPN: {self.event}"

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
