# Definitions to parse system events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.
#
# General subtypes use the 'module' field to provide additional context.
#   Here, the module is appended to 'general', eg, general_upgrade, general_auth, etc.


auth:
  description: "An event related to authentication, such as user login or logout, or GP auth."
  message: "{self.device_name} has reported {self.name} auth events. {self.description}"

ctd-agent:
  description: "Continuous Threat Detection agent. This process connects to the cloud for services like Wildfire."
  message: "{self.device_name} has reported a CTD agent event: {self.description}"

crypto:
  description: ""
  message: "System/Crypto event: {self.event}"

dhcp:
  description: ""
  message: "System/dhcp event: {self.event}"

dnsproxy:
  description: ""
  message: "System/dnsproxy event: {self.event}"

dos:
  description: ""
  message: "System/dos event: {self.event}"

general:
  description: ""
  message: "{self.device_name} has detected a general event: {self.description}"

general_general:
  description: ""
  message: "{self.device_name} has detected a general event: {self.description}"

general_management:
  description: ""
  message: "General management event detected: {self.event}"

general_auth:
  description: ""
  message: "General auth event detected: {self.event}"

general_ha:
  description: ""
  message: "General ha event detected: {self.event}"

general_upgrade:
  description: ""
  message: "General upgrade event detected: {self.event}"

general_chassis:
  description: ""
  message: "General chassis event detected: {self.event}"

global-protect:
  description: ""
  message: "System/Global Protect event: {self.event}"

ha:
  description: ""
  message: "{self.device_name} reports HA event: {self.description}"

hw:
  description: ""
  message: "System/Hardware event: {self.event}"

nat:
  description: ""
  message: "System/NAT event: {self.event}"

ntpd:
  description: ""
  message: "System/NTP event: {self.event}"

pbf:
  description: ""
  message: "System/PBF event: {self.event}"

port:
  description: ""
  message: "System/Port event: {self.event}"

pppoe:
  description: ""
  message: "System/pppoe event: {self.event}"

ras:
  description: ""
  message: "System/RAS event: {self.event}"

routing:
  description: "Routing events are related to the routing protocols and their operations. BGP, OSPF, etc."
  message: "{self.device_name} has experienced a {self.name} event. {self.description}"

satd:
  description: ""
  message: "System/satd event: {self.event}"

sslmgr:
  description: ""
  message: "System/SSL Manager event: {self.event}"

sslvpn:
  description: ""
  message: "System/SSL VPN event: {self.event}"

url-filtering:
  description: "An event relating to connecting to the PA cloud service for URL filtering."
  message: "URL filtering event: {self.device_name} {self.description}. ({self.name})"

vpn:
  description: "An event related to IPSec VPN tunnels"
  message: "{self.device_name} has reported a VPN event: {self.description}"

userid:
  description: "An alert for the User-ID system. This is not about users themselves."
  message: "User-ID: {self.device_name} has detected a {self.name} issue. \n\n{self.description}"

lacp:
  description: "A problem with LACP (Link Aggregation Control Protocol) has been detected."
  message: "{self.device_name} has detected an LACP {self.name} issue on {self.object}. \n\n{self.description}"

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
