# Definitions to parse Traffic events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.


Start:
  description: "Session has started"
  message: "Session started: {self.event}"

End:
  description: "Session has ended"
  message: "Session ended: {self.event}"

Drop:
  description: "A session has been dropped"
  message: "Session dropped: {self.event}"

Deny:
  description: "A session has been denied"
  message: "Session denied: {self.event}"

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
