# Definitions to parse wildfire events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.


malware:
  description: ""
  message: "Wildfire says {self.security_match_srcuser} transferred malware ({self.security_tuple_src} to {self.security_tuple_dst}) using {self.security_app}. {self.device_name} decided to {self.security_threat_action} the file."

phishing:
  description: ""
  message: "Wildfire/Phishing: {self.event}"

grayware:
  description: ""
  message: "Wildfire/Grayware: {self.event}"

benign:
  description: ""
  message: "Wildfire says {self.security_match_srcuser} transferred a benign file ({self.security_tuple_src} to {self.security_tuple_dst}) using {self.security_app}. {self.device_name} decided to {self.security_threat_action} the file."

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
