# Definitions to parse wildfire events from PA Firewall webhooks
#
# Definitions below contain:
# - description: A short description of the event. This is used for documentation purposes.
# - message: A message template that will be used to format the event message.
# - teams: Optional message template for Microsoft Teams notifications. If not provided, the other message will be used.


wildfire:
  description: ""
  message: "Wildfire event detected: {self.event}"

default:
  description: "A default event for firewall webhooks."
  message: "An unknown event has been received from a firewall."
